### ISSUE TITLE
Publish on GitHub pages?

### ISSUE THREAD

**Issue by bollwyvl** [mwaskom/seaborn-data#24]
Thanks for these datasets!

## Elevator Pitch

It would be lovely if the data sets were available from a GitHub Pages site.

## Motivation 

Pages have fewer CORS headers, requirements, etc. so might be accessible to more folks/environments.

The direct motivation is accessing the examples from `pyodide` (specifically [`jupyterlite`](https://github.com/jupyterlite/jupyterlite/pull/940)).

## Design Ideas

The Pages config itself (using the default branch as the pages source) might only need 
- a button press in the GitHub UI
- a (built) `index.html` to resolve as `https://mwaskom.github.io/seaborn-data/`

## Future Work

- A related change would be potentially preferring the pages URL
  - or making it an argument to `load_dataset` (and therefore) `get_dataset_names`. 
- As an aside: the `seaborn` documentation site could _also_ host a live pyodide demo/playground to augment the existing gallery, and the data sets could be sourced from there.

**Comment by koenvo** [comment]
Thanks for the nice description @bollwyvl, and thanks for this great repository of datasets!
 
Another could be to create a list of all available csv files in this repository, and add it as a csv/json to this repository. Makes it a bit easier to read/parse in `seaborn` at the cost of maintaining the list file. 

The file in a github repository are available via the `https://raw.githubusercontent.com/mwaskom/seaborn-data/master/...` urls and when requesting those the CORS headers are set.

**Comment by mwaskom** [comment]
What is the actual problem statement for the current way that things work? “ Pages have fewer CORS headers, requirements, etc.” is a meaningless statement to me.

**Comment by bollwyvl** [comment]
We can't add seaborn examples using these datasets, when hosted on ReadTheDocs, as in the above linked PR:

https://github.com/jupyterlite/jupyterlite/pull/940

If these were hosted on a different URL/CDN with less restrictive origin requirements, then we could.

**Comment by mwaskom** [comment]
If I'm understanding properly, the issue isn't with loading the datasets but with parsing the repo homepage to get a list of valid names. If that's the case, then @koenvo's suggestion of having a simple text file with a list of valid names seems like a simple way forward that should solve your problem?

**Comment by koenvo** [comment]
Yes that would work
