### ISSUE TITLE
Dataset descriptions.

### ISSUE THREAD

**Issue by SergiyKolesnikov** [mwaskom/seaborn-data#3]
Are these datasets described somewhere? What is the data, what does each column mean, etc?

**Comment by ghost** [comment]
Yes , this data set is available in seaborn library.You can load it by using :
import seaborn as sb
  tips = sns.load_dataset('tips')
this data is about the people who visits the restaurant onparticular day , time (i.e. dinner, lunch ,breakfast) ,size(number of people), tip(amount left for waiter) and rest you can understand. You need to predict the tip fpr each id

**Comment by Matt-V50** [comment]
> Yes , this data set is available in seaborn library.You can load it by using :
> import seaborn as sb
> tips = sns.load_dataset('tips')
> this data is about the people who visits the restaurant onparticular day , time (i.e. dinner, lunch ,breakfast) ,size(number of people), tip(amount left for waiter) and rest you can understand. You need to predict the tip fpr each id

@ghost

So where can I get the mean of each columns?

Thanks
